// Sample resumes to solve writer's block and provide realistic pre-filled data
export const SAMPLE_RESUMES = [
  {
    id: "software-engineer",
    role: "Software Engineer",
    category: "Engineering & Tech",
    badge: "Most Popular",
    color: "from-blue-600 to-indigo-600",
    lightBg: "bg-blue-50 border-blue-200 text-blue-700",
    headline: "Full Stack / React, Node.js & AWS",
    description: "Realistic experience with React, Node.js, TypeScript, AWS, high-throughput microservices, and system architecture.",
    template: "modern",
    data: {
      title: "Software Engineer Resume",
      template: "modern",
      personalInfo: {
        fullName: "Alex Rivera",
        jobTitle: "Senior Full Stack Engineer",
        email: "alex.rivera@example.com",
        phone: "+1 (555) 234-5678",
        location: "San Francisco, CA",
        linkedin: "linkedin.com/in/alexrivera-dev",
        website: "github.com/alexrivera",
      },
      summary: "Results-driven Full Stack Engineer with 5+ years of experience designing and deploying scalable web applications, microservices, and distributed cloud systems. Passionate about developer tooling, clean architecture, and performance optimization.",
      experience: [
        {
          title: "Senior Software Engineer",
          company: "StripeX Technologies",
          location: "San Francisco, CA",
          startDate: "2022-03",
          endDate: "",
          current: true,
          description: "• Architected high-throughput payment processing microservices handling 4M+ daily transactions with 99.99% uptime\n• Optimized React state management and bundle chunking, reducing First Contentful Paint by 42%\n• Mentored 6 junior engineers and spearheaded automated CI/CD pipelines that cut release cycles from 3 days to 45 mins",
        },
        {
          title: "Software Engineer",
          company: "Nimbus Cloud Systems",
          location: "San Jose, CA",
          startDate: "2019-06",
          endDate: "2022-02",
          current: false,
          description: "• Built robust RESTful APIs in Node.js/Express and integrated PostgreSQL caching with Redis, boosting query response times by 35%\n• Designed responsive, reusable UI component library in React & Tailwind CSS adopted by 4 cross-functional product squads\n• Reduced test regression run time by 50% by establishing comprehensive Jest and Cypress integration suites",
        },
      ],
      education: [
        {
          degree: "B.S. in Computer Science",
          school: "University of California, Berkeley",
          location: "Berkeley, CA",
          startDate: "2015-08",
          endDate: "2019-05",
          gpa: "3.8/4.0",
        },
      ],
      skills: [
        "JavaScript", "TypeScript", "React", "Node.js", "Express", "Next.js", "Python",
        "MongoDB", "PostgreSQL", "Docker", "AWS", "GraphQL", "Git", "REST APIs", "Tailwind CSS"
      ],
      projects: [
        {
          name: "DevPulse - Cloud Telemetry Dashboard",
          technologies: ["React", "TypeScript", "Node.js", "Docker", "MongoDB"],
          link: "github.com/alexrivera/devpulse",
          description: "Engineered a real-time server telemetry dashboard with WebSockets monitoring 500+ microservice nodes.",
        },
        {
          name: "SmartFlow - AI Workflow Orchestrator",
          technologies: ["Python", "FastAPI", "OpenAI", "Redis"],
          link: "github.com/alexrivera/smartflow",
          description: "Created automated background worker dispatching AI-augmented task pipelines with under 200ms latency.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "AWS Certified Solutions Architect – Associate",
          issuer: "Amazon Web Services",
          date: "2023-04",
        },
      ],
    },
  },
  {
    id: "data-analyst",
    role: "Data Analyst",
    category: "Data & Analytics",
    badge: "Trending",
    color: "from-emerald-600 to-teal-600",
    lightBg: "bg-emerald-50 border-emerald-200 text-emerald-700",
    headline: "SQL, Python, BI & Predictive Models",
    description: "Realistic experience in automated ETL pipelines, Tableau executive dashboards, A/B testing, and predictive customer retention.",
    template: "swiss",
    data: {
      title: "Data Analyst Resume",
      template: "swiss",
      personalInfo: {
        fullName: "Priya Sharma",
        jobTitle: "Senior Data Analyst",
        email: "priya.sharma@example.com",
        phone: "+1 (555) 456-7890",
        location: "New York, NY",
        linkedin: "linkedin.com/in/priyasharma-data",
        website: "priyasharma.io",
      },
      summary: "Analytical and detail-oriented Senior Data Analyst with 4+ years translating petabytes of complex datasets into actionable business intelligence, predictive forecasting models, and executive Tableau dashboards.",
      experience: [
        {
          title: "Lead Data Analyst",
          company: "Horizon Analytics & Capital",
          location: "New York, NY",
          startDate: "2022-01",
          endDate: "",
          current: true,
          description: "• Engineered automated ETL data pipelines in Python and Snowflake processing 12M+ monthly event logs\n• Designed interactive executive Tableau dashboards used by C-suite executives to optimize $45M annual marketing spend\n• Formulated predictive churn classification models using Scikit-Learn that decreased quarterly subscriber attrition by 18%",
        },
        {
          title: "Business Intelligence Analyst",
          company: "Metro Retail Solutions",
          location: "Boston, MA",
          startDate: "2020-02",
          endDate: "2021-12",
          current: false,
          description: "• Authored complex SQL queries and window functions across 8 relational databases to identify cross-sell opportunities yielding $1.2M in net revenue\n• Conducted end-to-end A/B tests on website checkout funnels, improving visitor conversion rate by 14%\n• Automated 15+ manual weekly Excel reporting packages into real-time PowerBI dashboards saving 20 team hours weekly",
        },
      ],
      education: [
        {
          degree: "B.S. in Statistics & Data Analytics",
          school: "New York University",
          location: "New York, NY",
          startDate: "2016-09",
          endDate: "2020-01",
          gpa: "3.75/4.0",
        },
      ],
      skills: [
        "SQL", "Python", "Tableau", "PowerBI", "R", "Snowflake", "Pandas",
        "NumPy", "Scikit-Learn", "ETL Pipelines", "A/B Testing", "Statistical Modeling", "Excel VBA"
      ],
      projects: [
        {
          name: "E-Commerce Customer Segmentation Engine",
          technologies: ["Python", "K-Means", "RFM Analysis", "Tableau"],
          link: "github.com/priyasharma/customer-rfm-segmentation",
          description: "Segmented 200,000+ customer transaction histories into 5 distinct behavioral clusters, boosting retention campaigns.",
        },
        {
          name: "Financial Fraud Detection Classifier",
          technologies: ["Python", "XGBoost", "SMOTE", "SQL"],
          link: "github.com/priyasharma/fraud-detection-model",
          description: "Trained an XGBoost model detecting fraudulent credit card transactions with a 98.4% ROC-AUC score.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "Tableau Desktop Certified Professional",
          issuer: "Tableau",
          date: "2022-08",
        },
      ],
    },
  },
  {
    id: "marketing-manager",
    role: "Marketing Manager",
    category: "Marketing & Growth",
    badge: "High Impact",
    color: "from-amber-600 to-orange-600",
    lightBg: "bg-amber-50 border-amber-200 text-amber-700",
    headline: "Growth, GTM, SEO & Content Strategy",
    description: "Realistic experience in multi-channel B2B SaaS growth, paid acquisition, HubSpot automation, and campaign ROI scaling.",
    template: "bold",
    data: {
      title: "Marketing Manager Resume",
      template: "bold",
      personalInfo: {
        fullName: "Marcus Vance",
        jobTitle: "Product Marketing Manager",
        email: "marcus.vance@example.com",
        phone: "+1 (555) 789-0123",
        location: "Austin, TX",
        linkedin: "linkedin.com/in/marcusvance-mktg",
        website: "marcusvance.com",
      },
      summary: "Strategic and growth-focused Marketing Manager with 6+ years driving B2B SaaS acquisition, brand positioning, and multi-channel go-to-market strategies. Proven track record of scaling inbound pipeline and decreasing customer acquisition costs.",
      experience: [
        {
          title: "Growth Marketing Manager",
          company: "Apex Software Labs",
          location: "Austin, TX",
          startDate: "2022-05",
          endDate: "",
          current: true,
          description: "• Spearheaded end-to-end GTM campaign for flagship enterprise software suite, generating $3.4M in pipeline within first 6 months\n• Directed paid acquisition strategies across Google Ads, LinkedIn, and Meta with a $150K monthly budget, reducing CAC by 28%\n• Orchestrated SEO content overhaul that quadrupled organic search traffic from 40K to 190K monthly visits",
        },
        {
          title: "Digital Marketing Specialist",
          company: "Vanguard Brand Studio",
          location: "Dallas, TX",
          startDate: "2018-08",
          endDate: "2022-04",
          current: false,
          description: "• Built automated email drip sequences in HubSpot and Marketo that boosted lead-to-opportunity conversion rate by 22%\n• Managed creative production of webinars, whitepapers, and customer case studies generating over 15,000 MQLs\n• Partnered with product and sales leadership to refine pricing tier positioning, driving a 19% uptick in annual contract value",
        },
      ],
      education: [
        {
          degree: "B.A. in Marketing & Communications",
          school: "University of Texas at Austin",
          location: "Austin, TX",
          startDate: "2014-08",
          endDate: "2018-05",
          gpa: "3.7/4.0",
        },
      ],
      skills: [
        "Go-to-Market Strategy", "SEO & SEM", "Google Analytics 4", "HubSpot", "Marketo",
        "Content Strategy", "A/B Testing", "Email Marketing", "PPC Campaigns", "Product Positioning"
      ],
      projects: [
        {
          name: "Global SaaS Product Launch 2.0",
          technologies: ["HubSpot", "Google Ads", "Unbounce", "Figma"],
          link: "marcusvance.com/case-studies/saas-launch",
          description: "Executed a comprehensive launch sprint delivering 4,200 product signups and top Product Hunt ranking.",
        },
        {
          name: "Organic Search Authority Engine",
          technologies: ["Ahrefs", "Semrush", "WordPress", "GA4"],
          link: "marcusvance.com/case-studies/seo-growth",
          description: "Produced a pillar-and-cluster content architecture that captured 45 page-one Google keyword rankings.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "Google Analytics & Ads Search Certified",
          issuer: "Google",
          date: "2023-01",
        },
      ],
    },
  },
  {
    id: "product-manager",
    role: "Product Manager",
    category: "Product & Strategy",
    badge: "High Demand",
    color: "from-purple-600 to-indigo-600",
    lightBg: "bg-purple-50 border-purple-200 text-purple-700",
    headline: "Roadmaps, Agile, PRDs & Retention",
    description: "Strategic leader driving customer discovery, cross-functional sprints, product-led growth, and scalable SaaS solutions.",
    template: "executive",
    data: {
      title: "Product Manager Resume",
      template: "executive",
      personalInfo: {
        fullName: "Sarah Chen",
        jobTitle: "Senior Technical Product Manager",
        email: "sarah.chen@example.com",
        phone: "+1 (555) 345-6789",
        location: "Seattle, WA",
        linkedin: "linkedin.com/in/sarahchen-pm",
        website: "sarahchenpm.com",
      },
      summary: "Data-driven Product Manager with 5+ years of experience leading cross-functional engineering and design squads to deliver high-impact SaaS products. Champion of customer empathy, rapid prototyping, and metric-oriented product roadmapping.",
      experience: [
        {
          title: "Senior Product Manager",
          company: "CloudScale Systems",
          location: "Seattle, WA",
          startDate: "2022-04",
          endDate: "",
          current: true,
          description: "• Defined product roadmap for core analytics platform serving 180K active monthly users, lifting customer retention by 24%\n• Led 14 engineers and 2 UX designers using Agile Scrum, increasing sprint velocity by 28% while reducing bug escapes\n• Spearheaded self-serve onboarding redesign that improved Day-30 user activation rate from 34% to 52%",
        },
        {
          title: "Product Manager",
          company: "Nova Commerce Labs",
          location: "Seattle, WA",
          startDate: "2019-07",
          endDate: "2022-03",
          current: false,
          description: "• Authored comprehensive PRDs and user stories for merchant checkout SDK generating $6.2M in annual recurring revenue\n• Conducted 80+ customer discovery interviews to synthesize feedback into high-priority feature backlogs\n• Partnered with marketing to execute multi-tier pricing migration, increasing average revenue per user (ARPU) by 17%",
        },
      ],
      education: [
        {
          degree: "B.S. in Information Systems & Business",
          school: "University of Washington",
          location: "Seattle, WA",
          startDate: "2015-09",
          endDate: "2019-06",
          gpa: "3.85/4.0",
        },
      ],
      skills: [
        "Product Roadmapping", "PRD Authoring", "Agile / Scrum", "User Research", "Data Analytics",
        "Jira", "Mixpanel", "Amplitude", "Figma", "A/B Testing", "SQL", "GTM Execution"
      ],
      projects: [
        {
          name: "Automated Feedback Sentiment Engine",
          technologies: ["Mixpanel", "Jira", "Figma", "SQL"],
          link: "sarahchenpm.com/projects/sentiment-engine",
          description: "Built automated pipeline categorizing NPS customer feedback into actionable roadmap epics.",
        },
        {
          name: "Frictionless B2B Onboarding Flow",
          technologies: ["Amplitude", "Segment", "FullStory"],
          link: "sarahchenpm.com/projects/onboarding-redesign",
          description: "Designed a 3-step interactive setup wizard cutting time-to-first-value from 12 minutes to 3.5 minutes.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "Certified Scrum Product Owner (CSPO)",
          issuer: "Scrum Alliance",
          date: "2022-11",
        },
      ],
    },
  },
  {
    id: "uiux-designer",
    role: "UI/UX Designer",
    category: "Design & Creative",
    badge: "Creative",
    color: "from-rose-500 to-pink-600",
    lightBg: "bg-rose-50 border-rose-200 text-rose-700",
    headline: "Design Systems, Figma & UX Research",
    description: "User-centric product designer creating cohesive design systems, accessible UI interactions, and mobile/web prototypes.",
    template: "nordic",
    data: {
      title: "UI/UX Designer Resume",
      template: "nordic",
      personalInfo: {
        fullName: "Elena Rostova",
        jobTitle: "Lead Product Designer",
        email: "elena.design@example.com",
        phone: "+1 (555) 987-6543",
        location: "Los Angeles, CA",
        linkedin: "linkedin.com/in/elenarostova-design",
        website: "elenarostova.design",
      },
      summary: "Human-centered UI/UX Designer with 6+ years creating intuitive digital experiences across web, iOS, and enterprise applications. Expert in establishing scalable tokenized design systems, wireframing, high-fidelity interactive prototyping, and usability testing.",
      experience: [
        {
          title: "Lead Product Designer",
          company: "PixelCraft Studio",
          location: "Los Angeles, CA",
          startDate: "2021-08",
          endDate: "",
          current: true,
          description: "• Architected multi-brand design system in Figma with 400+ reusable tokens, cutting frontend design handoff time by 50%\n• Redesigned enterprise healthcare portal for 500K patients, elevating usability score (SUS) from 58 to 86\n• Executed 45+ moderated user testing sessions, turning behavioural pain points into friction-free navigation flows",
        },
        {
          title: "UI/UX Designer",
          company: "Kinetix Digital Labs",
          location: "San Diego, CA",
          startDate: "2018-05",
          endDate: "2021-07",
          current: false,
          description: "• Designed native iOS and Android fintech app from ground up, contributing to 4.8-star App Store rating across 30K reviews\n• Built interactive micro-animations and motion guidelines in Principle & After Effects that improved session time by 22%\n• Collaborated closely with front-end engineers to ensure WCAG 2.1 AA accessibility compliance across all components",
        },
      ],
      education: [
        {
          degree: "B.F.A. in Interaction & Graphic Design",
          school: "Rhode Island School of Design (RISD)",
          location: "Providence, RI",
          startDate: "2014-09",
          endDate: "2018-05",
          gpa: "3.9/4.0",
        },
      ],
      skills: [
        "Figma", "Design Systems", "User Research", "Wireframing", "Interactive Prototyping",
        "Information Architecture", "Usability Testing", "WCAG Accessibility", "Design Tokens", "HTML/CSS"
      ],
      projects: [
        {
          name: "Lumina - Multi-Platform Design System",
          technologies: ["Figma", "Storybook", "Zeroheight", "Design Tokens"],
          link: "elenarostova.design/lumina-system",
          description: "Created comprehensive design tokens and component library published across 5 product teams.",
        },
        {
          name: "Aura - Mindfulness & Health iOS App",
          technologies: ["Figma", "Principle", "UserTesting.com"],
          link: "elenarostova.design/aura-app",
          description: "Crafted sensory-friendly interface and onboarding sequence for a daily habit tracking mobile application.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "Nielsen Norman Group UX Master Certified",
          issuer: "NN/g",
          date: "2023-03",
        },
      ],
    },
  },
  {
    id: "devops-engineer",
    role: "DevOps & Cloud Engineer",
    category: "Cloud & Infrastructure",
    badge: "Cloud & Infra",
    color: "from-cyan-600 to-blue-700",
    lightBg: "bg-cyan-50 border-cyan-200 text-cyan-700",
    headline: "AWS, Kubernetes, Terraform & CI/CD",
    description: "Reliability engineer specializing in multi-region Kubernetes, GitOps, infrastructure-as-code, and 99.99% system availability.",
    template: "mono",
    data: {
      title: "DevOps Engineer Resume",
      template: "mono",
      personalInfo: {
        fullName: "David Kim",
        jobTitle: "Senior DevOps & Cloud Architect",
        email: "david.kim.cloud@example.com",
        phone: "+1 (555) 678-9012",
        location: "Chicago, IL",
        linkedin: "linkedin.com/in/davidkim-devops",
        website: "github.com/davidkim-ops",
      },
      summary: "Results-oriented Cloud & DevOps Engineer with 6+ years specializing in AWS/GCP architecture, Kubernetes orchestration, Infrastructure as Code (Terraform), and automated GitOps CI/CD delivery pipelines for high-concurrency systems.",
      experience: [
        {
          title: "Staff Cloud Infrastructure Engineer",
          company: "Aether Cloud Infrastructure",
          location: "Chicago, IL",
          startDate: "2022-02",
          endDate: "",
          current: true,
          description: "• Architected multi-region AWS EKS Kubernetes clusters serving 150M daily API requests with 99.995% SLA\n• Automated infrastructure provisioning using Terraform modules and Helm, reducing environment spin-up from 4 days to 18 mins\n• Implemented proactive Prometheus and Grafana alerts, reducing Mean Time to Resolution (MTTR) by 62%",
        },
        {
          title: "DevOps Engineer",
          company: "OmniTech Solutions",
          location: "Detroit, MI",
          startDate: "2018-09",
          endDate: "2022-01",
          current: false,
          description: "• Migrated 45 monolithic microservices from on-premise VMs to Docker containers on AWS ECS\n• Built robust GitHub Actions and ArgoCD deployment pipelines with automated canary releases and security scanning\n• Optimized AWS cloud resource utilization, driving a sustained $180,000 annual cloud infrastructure cost reduction",
        },
      ],
      education: [
        {
          degree: "B.S. in Computer Engineering",
          school: "University of Illinois Urbana-Champaign",
          location: "Urbana, IL",
          startDate: "2014-08",
          endDate: "2018-05",
          gpa: "3.78/4.0",
        },
      ],
      skills: [
        "AWS", "Kubernetes (EKS)", "Docker", "Terraform", "CI/CD", "GitHub Actions",
        "ArgoCD", "Linux", "Python", "Bash", "Prometheus", "Grafana", "Helm", "GitOps"
      ],
      projects: [
        {
          name: "GitOps Self-Healing Cluster Controller",
          technologies: ["Kubernetes", "Go", "Helm", "ArgoCD"],
          link: "github.com/davidkim-ops/gitops-controller",
          description: "Constructed autonomous reconciler that rolls back out-of-sync cluster deployments in under 3 seconds.",
        },
        {
          name: "Terraform Multi-Cloud VPC Mesh",
          technologies: ["Terraform", "AWS", "GCP", "WireGuard"],
          link: "github.com/davidkim-ops/multicloud-mesh",
          description: "Provisioned encrypted inter-cloud VPC peering topology with automated failover routing.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "Certified Kubernetes Administrator (CKA)",
          issuer: "Linux Foundation / CNCF",
          date: "2023-05",
        },
      ],
    },
  },
  {
    id: "ai-engineer",
    role: "AI & ML Engineer",
    category: "Artificial Intelligence",
    badge: "Next-Gen AI",
    color: "from-violet-600 to-purple-800",
    lightBg: "bg-violet-50 border-violet-200 text-violet-700",
    headline: "LLMs, RAG, PyTorch & Vector DBs",
    description: "Machine learning engineer building production RAG pipelines, fine-tuned transformer models, and real-time AI inference engines.",
    template: "editorial",
    data: {
      title: "AI Engineer Resume",
      template: "editorial",
      personalInfo: {
        fullName: "Dr. Aryan Patel",
        jobTitle: "Senior AI & Machine Learning Engineer",
        email: "aryan.patel.ai@example.com",
        phone: "+1 (555) 890-1234",
        location: "Boston, MA",
        linkedin: "linkedin.com/in/aryanpatel-ai",
        website: "github.com/aryanpatel-ai",
      },
      summary: "Pioneering Machine Learning Engineer with 5+ years building and deploying deep learning models, LLM agents, and real-time vector search pipelines. Proven ability to take research prototypes from paper to production serving millions of queries.",
      experience: [
        {
          title: "Senior AI Research Engineer",
          company: "Synapse Intelligence Labs",
          location: "Boston, MA",
          startDate: "2022-06",
          endDate: "",
          current: true,
          description: "• Engineered production Enterprise RAG architecture with hybrid semantic search, reducing hallucination rate by 38%\n• Fine-tuned 7B/13B parameter open-source LLMs using LoRA/QLoRA on proprietary data, beating GPT-3.5 on specialized domain tasks\n• Optimized model inference with TensorRT-LLM and vLLM, doubling token generation throughput while cutting GPU costs by 45%",
        },
        {
          title: "Machine Learning Engineer",
          company: "Visionary Cognition AI",
          location: "Cambridge, MA",
          startDate: "2019-10",
          endDate: "2022-05",
          current: false,
          description: "• Developed convolutional neural network models for real-time document OCR achieving 99.2% character accuracy\n• Built automated feature stores and model registry workflows using MLflow and FastAPI deployed on AWS SageMaker\n• Published 2 papers at peer-reviewed AI workshops on efficient embedding distillation for edge devices",
        },
      ],
      education: [
        {
          degree: "M.S. in Computer Science (Machine Learning)",
          school: "Massachusetts Institute of Technology (MIT)",
          location: "Cambridge, MA",
          startDate: "2017-09",
          endDate: "2019-06",
          gpa: "3.92/4.0",
        },
      ],
      skills: [
        "Python", "PyTorch", "Hugging Face", "LangChain", "LlamaIndex", "Vector DBs (Pinecone, Qdrant)",
        "vLLM", "TensorRT", "FastAPI", "Docker", "CUDA", "Scikit-Learn", "MLflow", "RAG Systems"
      ],
      projects: [
        {
          name: "NeuralRAG - High-Speed Enterprise Knowledge Engine",
          technologies: ["Python", "PyTorch", "Qdrant", "FastAPI", "Docker"],
          link: "github.com/aryanpatel-ai/neuralrag",
          description: "Open-source RAG engine performing semantic retrieval across 10M+ documents with sub-120ms latency.",
        },
        {
          name: "LiteDistill - Small Language Model Distiller",
          technologies: ["PyTorch", "Hugging Face Transformers", "CUDA"],
          link: "github.com/aryanpatel-ai/litedistill",
          description: "Toolkit for distilling knowledge from large teacher models into edge-deployable compact architectures.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "Deep Learning Specialization",
          issuer: "DeepLearning.AI",
          date: "2021-04",
        },
      ],
    },
  },
  {
    id: "cybersecurity-analyst",
    role: "Cybersecurity Analyst",
    category: "Security & Compliance",
    badge: "Critical Role",
    color: "from-red-600 to-rose-700",
    lightBg: "bg-red-50 border-red-200 text-red-700",
    headline: "SIEM, Threat Hunting & Incident Response",
    description: "Security specialist defending critical networks, running vulnerability assessments, and implementing Zero Trust compliance.",
    template: "classic",
    data: {
      title: "Cybersecurity Analyst Resume",
      template: "classic",
      personalInfo: {
        fullName: "Jordan Miller",
        jobTitle: "Lead Cybersecurity Analyst",
        email: "jordan.miller.sec@example.com",
        phone: "+1 (555) 321-7654",
        location: "Washington, DC",
        linkedin: "linkedin.com/in/jordanmiller-sec",
        website: "jordansec.io",
      },
      summary: "Vigilant and certified Cybersecurity Analyst with 5+ years defending enterprise infrastructures against advanced persistent threats (APTs). Specialized in Security Operations Center (SOC) management, SIEM analytics (Splunk), threat hunting, and incident containment.",
      experience: [
        {
          title: "Senior SOC Threat Analyst",
          company: "Fortress Cyber Defense",
          location: "Washington, DC",
          startDate: "2021-11",
          endDate: "",
          current: true,
          description: "• Monitored SIEM telemetry across 2,500 endpoints, investigating and resolving 300+ high-severity security incidents\n• Engineered automated SOAR playbooks in Python, accelerating incident containment time from 35 minutes to under 4 minutes\n• Conducted regular adversary emulation and vulnerability assessments, remediating 94 critical CVE exposures",
        },
        {
          title: "Information Security Analyst",
          company: "Sentinel Global Systems",
          location: "Arlington, VA",
          startDate: "2018-07",
          endDate: "2021-10",
          current: false,
          description: "• Spearheaded Zero Trust Network Access (ZTNA) rollout and multi-factor authentication across 1,800 enterprise users\n• Led internal SOC 2 Type II compliance audit, achieving 100% adherence with zero negative findings\n• Designed interactive phishing awareness simulations, decreasing employee click-through susceptibility from 23% to 2.1%",
        },
      ],
      education: [
        {
          degree: "B.S. in Cybersecurity & Information Assurance",
          school: "George Mason University",
          location: "Fairfax, VA",
          startDate: "2014-08",
          endDate: "2018-05",
          gpa: "3.72/4.0",
        },
      ],
      skills: [
        "SIEM (Splunk, Sentinel)", "Threat Hunting", "Incident Response", "Wireshark", "NIST Framework",
        "Penetration Testing", "Vulnerability Management", "SOC 2 Compliance", "Python Scripting", "Firewalls"
      ],
      projects: [
        {
          name: "ThreatStream - Automated IOC Ingestion Bot",
          technologies: ["Python", "Splunk API", "VirusTotal API", "Docker"],
          link: "github.com/jordanmiller-sec/threatstream",
          description: "Automated real-time correlation engine pulling indicators of compromise into SIEM watchlists.",
        },
        {
          name: "ZeroTrust - Endpoint Compliance Auditor",
          technologies: ["Bash", "PowerShell", "Elasticsearch"],
          link: "github.com/jordanmiller-sec/zerotrust-auditor",
          description: "Lightweight daemon inspecting remote workstation security baseline adherence.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "CompTIA Security+ & CySA+",
          issuer: "CompTIA",
          date: "2022-09",
        },
      ],
    },
  },
  {
    id: "financial-analyst",
    role: "Financial Analyst",
    category: "Finance & Accounting",
    badge: "Finance & Growth",
    color: "from-emerald-700 to-green-800",
    lightBg: "bg-emerald-50 border-emerald-200 text-emerald-800",
    headline: "Financial Modeling, DCF & Forecasting",
    description: "Strategic finance professional building 3-statement models, capital allocation budgets, and M&A valuation scenarios.",
    template: "minimal",
    data: {
      title: "Financial Analyst Resume",
      template: "minimal",
      personalInfo: {
        fullName: "Kavita Iyer",
        jobTitle: "Senior Corporate Financial Analyst",
        email: "kavita.iyer.finance@example.com",
        phone: "+1 (555) 543-2109",
        location: "Charlotte, NC",
        linkedin: "linkedin.com/in/kavitaiyer-finance",
        website: "kavitafinance.com",
      },
      summary: "Detail-oriented Senior Financial Analyst with 5+ years of experience in corporate FP&A, financial modeling, and strategic capital allocation. Expert in three-statement forecasting, variance analysis, and delivering data-driven valuation insights to senior executive teams.",
      experience: [
        {
          title: "Senior Financial Analyst - FP&A",
          company: "Pinnacle Capital Group",
          location: "Charlotte, NC",
          startDate: "2022-01",
          endDate: "",
          current: true,
          description: "• Built 5-year three-statement integrated financial forecast model guiding corporate capital allocation for $85M annual budget\n• Performed monthly budget vs. actual variance analysis, identifying $1.8M in operational cost savings across 6 business units\n• Formulated DCF and Comparable Company valuation decks for 3 successful corporate acquisitions totaling $42M in enterprise value",
        },
        {
          title: "Financial Analyst",
          company: "Apex Investment Banking Advisory",
          location: "Atlanta, GA",
          startDate: "2019-06",
          endDate: "2021-12",
          current: false,
          description: "• Prepared pitch decks and financial sensitivity models for 12 middle-market debt and equity financing deals\n• Automated quarterly management reporting packs using Excel VBA macros and PowerBI, saving 35 analyst hours each cycle\n• Conducted deep market research and competitor benchmarking to support executive boardroom strategic planning",
        },
      ],
      education: [
        {
          degree: "B.S. in Finance & Economics",
          school: "University of North Carolina at Chapel Hill",
          location: "Chapel Hill, NC",
          startDate: "2015-08",
          endDate: "2019-05",
          gpa: "3.88/4.0",
        },
      ],
      skills: [
        "Financial Modeling", "DCF Valuation", "Budgeting & Forecasting", "Three-Statement Models",
        "Excel VBA", "PowerBI", "Variance Analysis", "M&A Due Diligence", "Capital Allocation", "SQL"
      ],
      projects: [
        {
          name: "SaaS Valuation & Unit Economics Dashboard",
          technologies: ["Excel VBA", "PowerBI", "Financial Modeling"],
          link: "kavitafinance.com/models/saas-unit-economics",
          description: "Dynamic financial model calculating CAC payback, LTV, and net revenue retention under multi-scenario stress tests.",
        },
        {
          name: "Automated Portfolio Rebalancing Model",
          technologies: ["Python", "Pandas", "Monte Carlo Simulation"],
          link: "github.com/kavitaiyer/portfolio-rebalancer",
          description: "Implemented Monte Carlo risk simulation optimizing asset allocation under varied inflation and rate regimes.",
        },
      ],
      certifications: [
        {
          type: "certification",
          name: "CFA Charterholder (Chartered Financial Analyst)",
          issuer: "CFA Institute",
          date: "2023-08",
        },
      ],
    },
  },
];
